📦 NEW: Fleet mode ⛵⛵⛵

diff --git a/cli b/cli
--- a/cli
+++ b/cli
@@ -1,8 +1,5 @@
 #!/usr/bin/env bash
 
-# Begin time tracking
-overalltimebegin=$(date +%s)
-
 ROOT_DIR=`dirname "$(perl -e 'use Cwd "abs_path"; print abs_path(shift)' $0)"`
 CLI_ENTRYPOINT=`basename $0`
 
@@ -64,41 +61,34 @@ for arg in "${CMD_ARGS[@]}"; do
         "$ROOT_DIR/help" $0 ${@:1:$((CMD_ARG_START - 1))} ${CMD_ARGS[@]}
         exit 3
     fi
-		if [[ "${arg}" == "--run-in-background="* ]]; then
-			run_in_background=${arg/--run-in-background=/}
-		fi
+    if [[ "${arg}" == "--fleet" ]]; then
+        fleet=true
+    fi
+    if [[ "${arg}" == "--captain_id"* ]]; then
+        captain_id=true
+    fi
     arg_i=$((arg_i+1))
 done
 
 # Run the command and capture its exit code for introspection
-if [[ $run_in_background != "" ]]; then
-	"$CMD_FILE" "${CMD_ARGS[@]%--run-in-background=*}" > ~/Tmp/job_$run_in_background.txt
-	# End time tracking
-	overalltimeend=$(date +%s)
-	runtime=$(($overalltimeend-$overalltimebegin))
-	last_line=$(tail -1 ~/Tmp/job_$run_in_background.txt)
-	# Checks last line
-	if [ ! -z "$last_line" ]; then
-		# Adds new line if needed
-		echo "" >> ~/Tmp/job_$run_in_background.txt
-	fi
-	echo "{\"response\":\"Command finished\",\"timestamp\":\"$(date +'%Y-%m-%d-%H%M%S')\",\"runtime\":\"$runtime\"}" >> ~/Tmp/job_$run_in_background.txt
-else
+if [[ $fleet == "true" ]] && [[ $captain_id == "true" ]]; then
+    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Can't use --fleet with --captain_id"
+    exit 3
+fi
+if [[ $fleet == "true" ]] && [[ $captain_id != "true" ]]; then
+    for captain_id in $(seq 1 3); do 
+	    "$CMD_FILE" "${CMD_ARGS[@]%--fleet*} --captain_id=$captain_id"
+    done
+    exit 3
+fi
+if [[ $fleet != "true" ]] && [[ $captain_id == "true" ]]; then
+	"$CMD_FILE" "${CMD_ARGS[@]}"
+fi
+if [[ $fleet != "true" ]] && [[ $captain_id == "" ]]; then
+    CMD_ARGS+=(--captain_id=1)
 	"$CMD_FILE" "${CMD_ARGS[@]}"
 fi
 EXIT_CODE=$?
-
-arg_i=0 # We need the index to be able to strip list indices
-for arg in "${CMD_ARGS[@]}"; do
-	if [[ "${arg}" == "--mark-when-completed" ]]; then
-		# End time tracking
-		overalltimeend=$(date +%s)
-		runtime=$(($overalltimeend-$overalltimebegin))
-		echo ""
-		echo "{\"response\":\"Command finished\",\"timestamp\":\"$(date +'%Y-%m-%d-%H%M%S')\",\"runtime\":\"$runtime\"}"
-	fi
-	arg_i=$((arg_i+1))
-done
 
 # If the command exited with an exit code of 3 (our "show help" code)
 # then show the help documentation for the command.
