👌 IMPROVE: Refactor commands

diff --git a/app/deactivate b/app/deactivate
--- a/app/deactivate
+++ b/app/deactivate
@@ -92,41 +92,33 @@ add_action( 'template_redirect', 'captaincore_template_redirect' );
 EOF
 
 run_command() {
-	for (( i = 1; i <= $#; i++ )); do
-	    var="$i"
-	    site=${!var}
 
-	    # Load site configs
-			eval $(captaincore site get $site --bash)
+	for website in "$@"; do
 
-	    # Site found, start the backup
-	    if ! [ -z "$domain" ]; then
+    # Load site configs
+		eval $(captaincore site get $website --bash)
 
-				if [[ "$homedir" != "" ]]; then
-					homedir="${homedir}/"
-				fi
+    # Site found, start the backup
+    if ! [ -z "$domain" ]; then
+			echo "Domain not found"
+      continue
+		fi
 
-	      ### upload deactivation plugin to mu-plugins
-	      rclone copyto ~/Tmp/captaincore_deactivated_${timestamp}.php sftp-$site:${homedir}wp-content/mu-plugins/captaincore_deactivated.php
+		if [[ "$homedir" != "" ]]; then
+			homedir="${homedir}/"
+		fi
 
-	      echo "deactivated $domain"
+    # Upload deactivation plugin to mu-plugins
+    rclone copyto ~/Tmp/captaincore_deactivated_${timestamp}.php sftp-$site:${homedir}wp-content/mu-plugins/captaincore_deactivated.php
 
-	    fi
-
-	    ### Clear out variables
-	    domain=''
-	    username=''
-	    password=''
-	    address=''
-	    protocol=''
-	    port=''
+    echo "deactivated $domain"
 
 	done
 
 }
 
-### See if any specific sites are selected
+# See if any specific sites are selected
 if [ $# -gt 0 ]; then
-    ## Run on selected site(s)
+    # Run on selected site(s)
     run_command ${arguments[*]}
 fi
