👌 IMPROVE: Snapshot names

diff --git a/app/snapshot b/app/snapshot
--- a/app/snapshot
+++ b/app/snapshot
@@ -72,19 +72,21 @@ run_command() {
     fi
 
     # Generates snapshot archive
-    timedate="$(date +'%Y-%m-%d-%H-%M-%S')-$( php -r 'echo bin2hex(openssl_random_pseudo_bytes( 32 ));' )"
+    timedate="$(date +'%Y-%m-%d-%H-%M-%S')-$( php -r 'echo bin2hex(openssl_random_pseudo_bytes( 4 ));' )"
+    snapshot_path="$site-$environment-$timedate"
+    snapshot_name="$site-$environment-$timedate.zip"
     cd $path/${site}_${site_id}/
 
     if [[ $delete_after_snapshot == true ]]; then
       cd $path/
-      zip --test -q -r $site-$environment-$timedate.zip ${site}_${site_id}/ && echo "Completed generating $site-$environment-$timedate.zip" || echo "Failed generating $site-$environment-$timedate.zip"
+      zip --test -q -r $snapshot_name ${site}_${site_id}/ && echo "Completed generating $snapshot_name" || echo "Failed generating $snapshot_name"
       mkdir -p ${site}_${site_id}-$timedate/${environment}/snapshots
-      mv $site-$environment-$timedate.zip ${environment}/snapshots
+      mv $snapshot_name ${environment}/snapshots
       cd ${environment}/snapshots
     fi
 
     if [[ $delete_after_snapshot != true ]]; then
-      ln -s $environment/backup/ $site-$environment-$timedate # create directory shortcut for naming purposes
+      ln -s $environment/backup/ $snapshot_path # create directory shortcut for naming purposes
 
       if [[ "$filter" != "" ]]; then
 
@@ -94,23 +96,23 @@ run_command() {
         for option in ${filters[@]}; do
 
           if [[ $option == "database" ]]; then
-            zip -r $site-$environment-$timedate.zip $site-$environment-$timedate/wp-content/mysql.sql
+            zip -r $snapshot_name $snapshot_path/wp-content/mysql.sql
           fi
 
           if [[ $option == "themes" ]]; then
-            zip --test -q -r $site-$environment-$timedate.zip $site-$environment-$timedate/wp-content/themes/ && echo "Completed generating $site-$environment-$timedate.zip" || echo "Failed generating $site-$environment-$timedate.zip"
+            zip --test -q -r $snapshot_name $snapshot_path/wp-content/themes/ && echo "Completed generating $snapshot_name" || echo "Failed generating $snapshot_name"
           fi
 
           if [[ $option == "plugins" ]]; then
-            zip --test -q -r $site-$environment-$timedate.zip $site-$environment-$timedate/wp-content/plugins/ && echo "Completed generating $site-$environment-$timedate.zip" || echo "Failed generating $site-$environment-$timedate.zip"
+            zip --test -q -r $snapshot_name $snapshot_path/wp-content/plugins/ && echo "Completed generating $snapshot_name" || echo "Failed generating $snapshot_name"
           fi
 
           if [[ $option == "uploads" ]]; then
-            zip --test -q -r $site-$environment-$timedate.zip $site-$environment-$timedate/wp-content/uploads/ && echo "Completed generating $site-$environment-$timedate.zip" || echo "Failed generating $site-$environment-$timedate.zip"
+            zip --test -q -r $snapshot_name $snapshot_path/wp-content/uploads/ && echo "Completed generating $snapshot_name" || echo "Failed generating $snapshot_name"
           fi
 
           if [[ $option == "everything-else" ]]; then
-            zip --test -q -r $site-$environment-$timedate.zip $site-$environment-$timedate/ --exclude=$site-$environment-$timedate/wp-content/mysql.sql --exclude=$site-$environment-$timedate/wp-content/themes/\* --exclude=$site-$environment-$timedate/wp-content/plugins/\* --exclude=$site-$environment-$timedate/wp-content/uploads/\* --exclude=$site-$environment-$timedate/_wpeprivate/\* --exclude=\*.git\* --exclude=$site-$environment-$timedate/wp-content/advanced-cache.php --exclude=$site-$environment-$timedate/wp-content/mu-plugins/mu-plugin.php --exclude=$site-$environment-$timedate/wp-content/mu-plugins/kinsta-mu-plugins.php --exclude=$site-$environment-$timedate/wp-content/mu-plugins/kinsta-mu-plugins/\* --exclude=$site-$environment-$timedate/wp-content/mu-plugins/slt-force-strong-passwords.php --exclude=$site-$environment-$timedate/wp-content/mu-plugins/force-strong-passwords/\* --exclude=$site-$environment-$timedate/wp-content/mu-plugins/wpengine-common/\* && echo "Completed generating $site-$environment-$timedate.zip" || echo "Failed generating $site-$environment-$timedate.zip"
+            zip --test -q -r $snapshot_name $snapshot_path/ --exclude=$snapshot_path/wp-content/mysql.sql --exclude=$snapshot_path/wp-content/themes/\* --exclude=$snapshot_path/wp-content/plugins/\* --exclude=$snapshot_path/wp-content/uploads/\* --exclude=$snapshot_path/_wpeprivate/\* --exclude=\*.git\* --exclude=$snapshot_path/wp-content/advanced-cache.php --exclude=$snapshot_path/wp-content/mu-plugins/mu-plugin.php --exclude=$snapshot_path/wp-content/mu-plugins/kinsta-mu-plugins.php --exclude=$snapshot_path/wp-content/mu-plugins/kinsta-mu-plugins/\* --exclude=$snapshot_path/wp-content/mu-plugins/slt-force-strong-passwords.php --exclude=$snapshot_path/wp-content/mu-plugins/force-strong-passwords/\* --exclude=$snapshot_path/wp-content/mu-plugins/wpengine-common/\* && echo "Completed generating $snapshot_name" || echo "Failed generating $snapshot_name"
           fi
 
         done
@@ -118,31 +120,32 @@ run_command() {
       fi
 
       if [[ "$filter" == "" ]]; then
+      
         # Add everything to ZIP
-        zip --test -q -r $site-$environment-$timedate.zip $site-$environment-$timedate/ --exclude=$site-$environment-$timedate/_wpeprivate/\* --exclude=\*.git\* --exclude=$site-$environment-$timedate/wp-content/advanced-cache.php --exclude=$site-$environment-$timedate/wp-content/mu-plugins/mu-plugin.php --exclude=$site-$environment-$timedate/wp-content/mu-plugins/kinsta-mu-plugins.php --exclude=$site-$environment-$timedate/wp-content/mu-plugins/kinsta-mu-plugins/\* --exclude=$site-$environment-$timedate/wp-content/mu-plugins/slt-force-strong-passwords.php --exclude=$site-$environment-$timedate/wp-content/mu-plugins/force-strong-passwords/\* --exclude=$site-$environment-$timedate/wp-content/mu-plugins/wpengine-common/\*
+        zip --test -q -r $snapshot_name $snapshot_path/ --exclude=$snapshot_path/_wpeprivate/\* --exclude=\*.git\* --exclude=$snapshot_path/wp-content/advanced-cache.php --exclude=$snapshot_path/wp-content/mu-plugins/mu-plugin.php --exclude=$snapshot_path/wp-content/mu-plugins/kinsta-mu-plugins.php --exclude=$snapshot_path/wp-content/mu-plugins/kinsta-mu-plugins/\* --exclude=$snapshot_path/wp-content/mu-plugins/slt-force-strong-passwords.php --exclude=$snapshot_path/wp-content/mu-plugins/force-strong-passwords/\* --exclude=$snapshot_path/wp-content/mu-plugins/wpengine-common/\*
       fi
       
-      rm $site-$environment-$timedate  # remove directory shortcut
+      rm $snapshot_path  # remove directory shortcut
       mkdir -p ${environment}/snapshots
-      mv $site-$environment-$timedate.zip ${environment}/snapshots
+      mv $snapshot_name ${environment}/snapshots
       cd ${environment}/snapshots
     fi
 
     # Grab snapshot size in bytes
     if [[ "$OSTYPE" == "linux-gnu" ]]; then
       # Begin folder size in bytes without apparent-size flag
-      snapshot_size=`du -s --block-size=1 $site-$environment-$timedate.zip`
+      snapshot_size=`du -s --block-size=1 $snapshot_name`
       snapshot_size=`echo $snapshot_size | cut -d' ' -f 1`
 
     elif [[ "$OSTYPE" == "darwin"* ]]; then
       # Calculate folder size in bytes http://superuser.com/questions/22460/how-do-i-get-the-size-of-a-linux-or-mac-os-x-directory-from-the-command-line
-      snapshot_size=`find $site-$environment-$timedate.zip -type f -print0 | xargs -0 stat -f%z`
+      snapshot_size=`find $snapshot_name -type f -print0 | xargs -0 stat -f%z`
     fi
 
     if [[ $skip_remote != true ]]; then
 
       # Moves snapshot to Backblaze archive folder
-      rclone move $site-$environment-$timedate.zip $rclone_snapshot/${site}_${site_id}/
+      rclone move $snapshot_name $rclone_snapshot/${site}_${site_id}/
 
       if [[ "$debug" == "true" ]]; then
 			read -r -d '' VAR << EOM
