👌 IMPROVE: Use bulk command

diff --git a/app/ssh b/app/ssh
--- a/app/ssh
+++ b/app/ssh
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
 #
-#   SSH connection to one or more sites
+#   SSH connection to one or more sites.
 #
-#   `captaincore ssh`
+#   `captaincore ssh <site>`
 #
 #   [<site>...]
 #   One or more sites.
@@ -17,14 +17,14 @@
 #   [--command=<commands>]
 #   Runs command over SSH
 #
-#   [--script=<name|script>] [--<script-argument-name>=<script-argument-value>...]
-#   Runs user-defined recipe
+#   [--script=<name|script>] [--<script-argument-name>=<script-argument-value>]
+#   Runs script over SSH
 #
 #   [--recipe=<recipe_id>
 #   Runs script over SSH
 #
 #   [--debug]
-#   Extra reporting for debug purposes
+#   Outputs SSH command for debug purposes
 #
 
 # Load configuration
@@ -32,52 +32,158 @@ root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_
 source ${root_path}lib/arguments
 
 run_command() {
+  
+	site=$1
 
-	websites=$@
+	# Extract environment
+	if [[ "$site" == *"-staging"* ]]; then
+		environment=staging
+	else
+		environment=production
+	fi
 
-	# Assign default parallel if needed
-  if [[ $parallel == "" ]]; then
-    parallel=3
-  fi
-  echo $websites | xargs -P $parallel -n 1 captaincore ssh-runner "${flags[@]}"
+	# Load site configs
+	while read site_configs; do if [[ $site_configs == "" ]]; then continue; fi; declare "$site_configs"; done <<< "$(captaincore site get $site --bash --captain_id=$captain_id)"
+
+    if [ -f "${path}/process-${process_id}-progress.log" ]; then
+      echo -n "." >> ${path}/process-${process_id}-progress.log
+    fi
+
+    if [[ "$address" == "" && "$captaincore_master" != "" ]]; then
+      echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Site $site not found."
+      exit
+    fi
+
+    if [[ "$protocol" != "sftp" ]]; then
+      echo -e "${COLOR_RED}Error:${COLOR_NORMAL} SSH not supported (Protocol is $protocol)."
+      exit
+    fi
+
+    if [[ "$provider" == "kinsta" && "$address" == "" ]]; then
+      echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Missing Kinsta site."
+      exit
+    fi
+
+    if [[ "$provider" == "wpengine" && "$environment" == "staging" ]]; then
+      echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Missing WP Engine site."
+      exit
+    fi
+
+    if [[ "$environment_vars" != "" ]]; then
+      environment_vars="$environment_vars &&"
+    fi
+
+    # If website on Kinsta then prepare their format
+    if [[ "$provider" == "kinsta" ]]; then
+
+      # Kinsta's command prep
+      command_prep="$environment_vars cd public/ &&"
+      remote_options="-oStrictHostKeyChecking=no -oPreferredAuthentications=publickey"
+      
+      if [[ $key != "" ]]; then
+         remote_options="$remote_options -i $path_keys/${captain_id}/${key}"
+      fi
+      
+      remote_server="$remote_options $username@$address -p $port"
+
+      if [[ "$use_staging" == "true" ]]; then
+        remote_server="$remote_options $username_staging@$address_staging -p $port_staging"
+      fi
+
+    fi
+
+    # If website on WP Engine then prepare their format
+    if [[ "$provider" == "wpengine" ]]; then
+
+      # WP Engine's command prep
+      command_prep="$environment_vars rm ~/.wp-cli/config.yml; cd sites/* &&"
+      remote_options="-oStrictHostKeyChecking=no -oPreferredAuthentications=publickey"
+
+      if [[ $key != "" ]]; then
+         remote_options="$remote_options -i $path_keys/${captain_id}/${key}"
+      fi
+
+      # WP Engine ssh address format
+      remote_server="$remote_options ${site}@${site}.ssh.wpengine.net"
+
+      if [[ "$use_staging" == "true" ]]; then
+        remote_server="$remote_options ${site_staging}@${site_staging}.ssh.wpengine.net"
+      fi
+
+    fi
+
+    if [[ "$remote_server" == "" ]]; then
+      echo -e "${COLOR_RED}Error:${COLOR_NORMAL} $domain website host provider not recognized."
+      exit
+    fi
+
+    if [[ "$command_prep" == "" ]]; then
+      echo -e "${COLOR_RED}Error:${COLOR_NORMAL} $domain website host provider not recognized."
+      exit
+
+    fi
+
+    # Runs ssh with recipe
+    if [[ "$recipe" != "" ]]; then
+      recipe_file="$path_recipes/${captain_id}-${recipe}.sh"
+      # Check for file
+      if [ -f "$recipe_file" ]; then
+        # Pass all arguments found after --script=<script> argument into remote script
+        ssh $remote_server "$command_prep bash -s -- --site=$site ${flags[@]}" < $recipe_file || true
+      fi
+      exit
+    fi
+
+    # Runs ssh with script
+    if [ -n "$script" ]; then
+      # Check for file
+      if [ ! -f "$script" ]; then
+        # Not found so attempt to run a local script
+        script=${root_path}lib/remote-scripts/$script
+      fi
+      # Pass all arguments found after --script=<script> argument into remote script
+      ssh $remote_server "$command_prep bash -s -- --site=$site ${flags[@]}" < $script || true
+      exit
+    fi
+
+    # Runs ssh with command
+    if [ -n "$command" ]; then
+      ssh $remote_server "$command_prep $command" || true
+      exit
+    fi
+
+    if [[ "$direct" == "true" ]]; then
+      ssh -T $remote_server || true
+      exit
+    fi
+
+    if [[ "$debug" == "true" ]]; then
+      echo "ssh $remote_server"
+    fi
+
+    # Runs ssh
+    ssh $remote_server
 
 }
 
-# Runs on targeted sites
-if [ ${#targets[*]} -gt 0 ] && ( [[ $command != "" ]] || [[ $script != "" ]] || [[ $recipe != "" ]] ); then
-  run_command $(captaincore site list ${targets[*]/targets=/@} --captain_id=$captain_id)
-  if [[ $debug == "true" ]]; then
-    echo "run_command $(captaincore site list ${targets[*]/targets=/@} --captain_id=$captain_id)"
-  fi
-  exit
-fi
-
-# Connects to SSH directly
-if [ ${#targets[*]} -eq 0 ] && [ ${#arguments[*]} -gt 0 ] && [ ${#flags[@]} -eq 1 ]; then
-  captaincore ssh-runner ${arguments[*]} --captain_id=$captain_id
-  if [[ $debug == "true" ]]; then
-    echo "captaincore ssh-runner ${arguments[*]} --captain_id=$captain_id"
-  fi
-  exit
-fi
-
-# Runs on specific sites
-if [ ${#targets[*]} -eq 0 ] && [ ${#arguments[*]} -gt 0 ]; then
-  run_command ${arguments[*]}
-  if [[ $debug == "true" ]]; then
-    echo "run_command ${arguments[*]}"
-  fi
-  exit
-fi
-
-# Error if no sites specifed
-if [ ${#targets[*]} -eq 0 ]; then
+if [ ${#arguments[*]} -eq 0 ] && [ ${#targets[*]} -eq 0 ]; then
   echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify one or more sites, or use a target @all, @production or @staging."
   exit
 fi
 
-# Error if no sites specifed
+if [ ${#arguments[*]} -eq 1 ] && [ ${#targets[*]} -eq 0 ]; then
+  run_command ${arguments[*]}
+fi
+
+if [ ${#arguments[*]} -gt 1 ] && [ ${#targets[*]} -eq 0 ] && [[ "$command" == "" ]] && [[ "$script" == "" ]] && [[ "$recipe" == "" ]]; then
+  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} For bulk sites please specify a [--command=<command>], [--script=<script>] or [--recipe=<recipe>]."
+  exit
+fi
+
+if [ ${#arguments[*]} -gt 1 ] && [ ${#targets[*]} -eq 0 ]; then
+  captaincore bulk ssh ${arguments[*]} "${flags[@]}"
+fi
+
 if [ ${#targets[*]} -gt 0 ] && [ ${#arguments[*]} -eq 0 ]; then
-  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify at least one `--command`, `--script` or `--recipe` when using @target."
-  exit 1
+  captaincore bulk ssh ${targets[*]/targets=/@} "${flags[@]}"
 fi
